### ISSUE TITLE
Where is the blacklist located?

### ISSUE THREAD

**Issue by supriyo-biswas** [ggsava/block-this#19]
Where is the block-this blacklist located?

I tried searching for the blacklist in the source tree, but I didn't find it. A cursory search for URLs from where the addresses are fetched also fails to turn up anything.

**Comment by wolojoli** [comment]
There is no blacklist as far as I know, only a white-list.

**Comment by ggsava** [comment]
There is no blacklist. The blacklist is managed on my own and is on the DNS server itself, not in the app. There are currently no plans to add custom blacklist inside the app.

**Comment by meitar** [comment]
I would have loved to use this app but I don't want to send you all my DNS queries. That is a serious privacy violation. It seems inconsistent at best for an app that is described as a privacy-enhancing tool to require users to wholly trust a DNS resolver that is unaccountable to them for that very same privacy. Please consider adding an option to download the blacklist you construct and refer to its local copy instead of sending your servers my DNS queries. This is more aligned with how other popular adblockers such as uBlock Origin work; they download rule lists locally and then do not need to make network requests at all.

Thanks.
