### ISSUE TITLE
DNS, remote servers, Pi-hole?

### ISSUE THREAD

**Issue by fivefilters** [ggsava/block-this#9]
Hi there, firstly, this really looks great! Thanks for sharing it.

I had a few questions around the DNS implementation that I wondered if you could help with:
1. Is there a reason why the DNS servers have to be remote? Would it not be possible to have the DNS server running as part of the app?
2. If not, would you be interested in changes to Block This to make the DNS servers configurable in the app? So users could point them to ones they manage themselves?
3. Related to the above, are you able to share how you implemented the ad-blocking DNS server? I'm quite interested in testing [Pi-hole](https://pi-hole.net/) as a self-hosted DNS ad blocker, perhaps running on a VPS. Have you looked into it? Any pros/cons compared to your solution?

Thanks again,

Keyvan

**Comment by vith** [comment]
About 1. I'm wondering the same thing.

I was surprised to find the public DNS server IPs in the source code; my initial reading of the website had me assuming it was a local DNS server because why wouldn't it be. I think it's easy to get the wrong idea and introduces an unnecessary privacy concern.

**Comment by fivefilters** [comment]
I saw a link on Sava's GitHub page to a similar project called [AdBuster](https://github.com/dbrodie/AdBuster) which appears to use a local DNS server for the blocking. Not sure how much it differs from this project other than that. But I'm keeping an eye on it too.

**Comment by ggsava** [comment]
1. Having the DNS locally will put a huge strain on your CPU and will drain your battery very quickly. Also I would have to send you updates every day to keep the black list up to date. 

2. Makes no sense, since the effort for this would be huge and I don't see any benefit. How many users really want to download an app that they have to configure for days, and how many people can set up their own DNS servers?

3. I haven't had the time to look into Pi-hole, but it sounds like a promising project. How the DNS is implemented and how it works is described on the app homepage https://block-this.com.

P.s. I'm closing this ticket, and please don't use github for questions but rather for bug reports. For questions use email or the forums. Thanks.
